import { ReportType } from "../../@types/report.type";
import { formatCurrency } from "../../utils/format-currency";
import { capitalizeFirstLetter } from "../../utils/helper";

export const reportTemplate = (reportData: any): string => {
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>FinGenius Financial Report</title>
      <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background: #f8f9fa; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
        .summary { background: #fff; padding: 20px; border: 1px solid #ddd; border-radius: 8px; margin-bottom: 20px; }
        .metric { display: flex; justify-content: space-between; margin-bottom: 10px; }
        .metric strong { color: #007bff; }
        .footer { text-align: center; color: #666; font-size: 12px; margin-top: 30px; }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1>📊 FinGenius Financial Report</h1>
          <p>Your financial summary for ${reportData.period || 'this period'}</p>
        </div>
        
        <div class="summary">
          <h2>💰 Financial Summary</h2>
          <div class="metric">
            <span>Total Income:</span>
            <strong>$${reportData.summary?.income || 0}</strong>
          </div>
          <div class="metric">
            <span>Total Expenses:</span>
            <strong>$${reportData.summary?.expenses || 0}</strong>
          </div>
          <div class="metric">
            <span>Available Balance:</span>
            <strong>$${reportData.summary?.balance || 0}</strong>
          </div>
          <div class="metric">
            <span>Savings Rate:</span>
            <strong>${reportData.summary?.savingsRate || 0}%</strong>
          </div>
        </div>
        
        <div class="footer">
          <p>Generated by FinGenius - Your Personal Finance Assistant</p>
          <p>This is an automated report. Please do not reply to this email.</p>
        </div>
      </div>
    </body>
    </html>
  `;
};
