export enum ErrorCodeEnum {
  VALIDATION_ERROR = "VALIDATION_ERROR",
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  ACCESS_UNAUTHORIZED = "ACCESS_UNAUTHORIZED",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  FILE_UPLOAD_ERROR = "FILE_UPLOAD_ERROR",
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
  AUTH_RATE_LIMIT_EXCEEDED = "AUTH_RATE_LIMIT_EXCEEDED",
  UPLOAD_RATE_LIMIT_EXCEEDED = "UPLOAD_RATE_LIMIT_EXCEEDED",
}

export type ErrorCodeEnumType = keyof typeof ErrorCodeEnum;
